# My machine uptime stats

<< echo "> This site was last updated at $($DATE $DATE_FORMAT)"

The following stats were collected via `uptimed` on all of my personal computers over many years and the output was generated by `guprecords`, the global uptime records stats analyser of mine.

> Uptimed is an uptime record daemon keeping track of the highest uptimes a computer system ever had. It uses the system boot time to keep sessions apart from each other.

=> https://github.com/rpodgorny/uptimed
=> https://codeberg.org/snonux/guprecords

Also check out my blog post:

=> ./gemfeed/2023-05-01-unveiling-guprecords:-uptime-records-with-raku.gmi Unveiling `guprecords.raku`: Uptime records with Raku

<<<
  if [ -f ~/git/uprecords/uprecords.gmi ]; then
      cat ~/git/uprecords/uprecords.gmi
  else
      $SED -n '/Top/,$p' uptime-stats.gmi
  fi
>>>
