# My machine uptime stats

<< echo "> This site was last updated at $($DATE $DATE_FORMAT)"

The following stats were collected via `uptimed` on all of my personal computers over many years and the output was generated by `guprecords`, the global uptime records stats analyser.

> Uptimed is an uptime record daemon keeping track of the highest uptimes a computer system ever had. It uses the system boot time to keep sessions apart from each other.

=> https://github.com/rpodgorny/uptimed
=> https://codeberg.org/snonux/guprecords

<<<
  if [ -f ~/git/uprecords/uprecords.gmi ]; then
      cat ~/git/uprecords/uprecords.gmi
  else
      $SED -n '/Top/,$p' uptime-stats.gmi
  fi
>>>
