# f3s: Kubernetes with FreeBSD - Part 5: WireGuard mesh network

This is the fith blog post about my f3s series for my self-hosting demands in my home lab. f3s? The "f" stands for FreeBSD, and the "3s" stands for k3s, the Kubernetes distribution I will use on FreeBSD-based physical machines.

I will post a new entry every month or so (there are too many other side projects for more frequent updates—I bet you can understand).

These are all the posts so far:

<< template::inline::rindex f3s

=> ./f3s-kubernetes-with-freebsd-part-1/f3slogo.png f3s logo

> Logo was generated by ChatGPT.

Let's begin...

<< template::inline::toc

## TODO

* what is wireguard...

* k3s by default traffic not encrypted

* maybe connect other boxes off-site via wireguard vpn tunnel

* Why not Tailscale
	* I Like magic, but only when I understand it
	* Learning / Curiosity (this is the 2nd whole point why I am doing this series, besides of self-hosting privacy)
	* Part of OS packages
	* Easier to maintain in the longer run as there are no ready to use packages for the BSDs..?

Other *BSD-related posts:

<< template::inline::rindex bsd

E-Mail your comments to `paul@nospam.buetow.org`

=> ../ Back to the main site
